language: cpp
compiler: gcc

install:
  # arduino
  - sudo apt-get install arduino
  # ino
  - cd ..
  - git clone git://github.com/amperka/ino.git
  - cd ino
  - sudo make install
  - sudo easy_install `cat requirements.txt`
  - cd ..
  - cd MysteryMachine2
  # CapacitiveSensor library
  - sudo git clone https://github.com/arduino-libraries/CapacitiveSensor.git /usr/share/arduino/libraries/CapacitiveSensor

script: 
  - cd CapacitiveSensors
  - ino build
